#!/usr/bin/env node
/* 
 * (C) 2018 TekMonks. All rights reserved.
 * License: MIT - see enclosed LICENSE file.
 */

const fs = require("fs");
const path = require("path");
const colors = require("colors");
let args = new (require("commander").Command);

global.CONSTANTS = require(`${__dirname}/lib/constants.js`);
global.CONF = require(`${CONSTANTS.CONFDIR}/xforge.json`);

const _printBuildTime = timeStarted => { if (args.time) CONSTANTS.LOGINFO(`Total build time: ${Date.now() - timeStarted} milliseconds`); }

module.exports.xforge = async function(inprocessArgs) {
    args.storeOptionsAsProperties(); 
    args.description("XForge - (C) TekMonks\nJust like make, except if it was on steriods ;)")
    args.version("XForge v2.4.9");
    args.option("-f, --file <path>", "required, full path to the build file");
    args.option("-c, --colors", "produce colored output");
    args.option("-t, --time", "track build time");
    args.option("-i, --incremental <value>", "true for incremental and false to force a full build");
    args.option("-o, --other <args>", "other arguments, passed to the build files", (otherArgs, other) => {other.push(otherArgs); return other;}, []);
    if (inprocessArgs) {args = inprocessArgs; args.outputHelp =_=>CONSTANTS.LOGERROR("Bad arguments to XForge");} else args.parse(process.argv);

    if (args.colors) CONSTANTS.COLORED_OUT = true;

    if (args.other) CONSTANTS.OTHER_ARGS = args.other;

    _overrideConfig();  // override config

    if (args.file) {
        const fileToBuild = _resolvePath(args.file);

        const timeStarted = Date.now();
        CONSTANTS.LOGINFO(`XForge starting build: ${fileToBuild}`);
        try { const retCode = await require(fileToBuild).make(...args.other); _printBuildTime(timeStarted); return retCode!==undefined?retCode:CONSTANTS.EXITOK(); } 
        catch (err) { _printBuildTime(timeStarted); return CONSTANTS.HANDLE_BUILD_ERROR(err); }
    } else {console.log(args.colors?colors.red(args.helpInformation()):args.helpInformation()); return CONSTANTS.EXITFAILED();}
}
 
function _resolvePath(file) {
    if (fs.existsSync(file)) return path.resolve(file);
    else return (path.resolve(`${__dirname}/${file}`));
}

function _overrideConfig() {
    if (args.incremental && args.incremental.toLowerCase() == "false") global.CONF.incremental_mode = false;
    if (args.incremental && args.incremental.toLowerCase() == "true") global.CONF.incremental_mode = true;
}

if (require.main === module) module.exports.xforge(); else CONSTANTS.INPROCESSMODE = true;